# Generated by Django 2.2.7 on 2019-12-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('booid', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=64)),
                ('writer', models.CharField(max_length=64)),
                ('press', models.CharField(max_length=64)),
                ('coverurl', models.CharField(default='', max_length=64)),
                ('description', models.CharField(default='', max_length=512)),
                ('neededcredit', models.IntegerField(default=0)),
            ],
        ),
    ]
