# Generated by Django 2.2.7 on 2019-12-26 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=-1)),
                ('otype', models.IntegerField()),
                ('expresscompany', models.IntegerField(default=-1)),
                ('trackingnumber', models.CharField(default='', max_length=64)),
                ('botid', models.IntegerField()),
                ('address', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=64)),
                ('phonenumber', models.CharField(max_length=32)),
                ('state', models.IntegerField()),
                ('submittime', models.DateTimeField(default=django.utils.timezone.now)),
                ('completetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
