# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=256)),
                ('credit', models.IntegerField(default=0)),
                ('enrolldatetime', models.DateTimeField()),
            ],
        ),
    ]
