# Generated by Django 2.2.7 on 2019-12-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(default='{"address":[]}', max_length=1024)),
                ('credit', models.IntegerField(default=0)),
                ('enrolldatetime', models.DateTimeField()),
                ('issuper', models.BooleanField(default=False)),
            ],
        ),
    ]
