# Generated by Django 2.2.7 on 2019-12-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=1024),
        ),
    ]
